import AblaCompanion from '../components/companion/AblaCompanion.jsx'
import { companionAccessories, companionPoses, eyeExpressions, mouthExpressions } from '../components/companion/companionVariants.js'

const personalities = ['friendly', 'curious', 'empathetic', 'motivating', 'calm', 'protective']
const moods = ['happy', 'neutral', 'worried', 'sad', 'confused', 'focused', 'relieved']

function ShowcaseRow({ title, items, render }) {
  return <section className="mt-10"><h2 className="text-xs font-black uppercase tracking-[.18em] text-abla-green">{title}</h2><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{items.map((item) => <div key={item} className="grid min-h-44 place-items-center rounded-abla-card bg-white p-4 text-center shadow-abla-card"><div>{render(item)}</div><span className="mt-2 text-xs font-bold capitalize text-abla-blue">{item}</span></div>)}</div></section>
}

export default function CompanionShowcase() {
  return <main className="min-h-dvh bg-abla-bg px-5 py-10 md:px-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.16em] text-abla-green">ABLA · Fase 2</p><div className="mt-3 grid items-center gap-6 rounded-abla-panel bg-white p-6 shadow-abla-card md:grid-cols-[1fr_320px] md:p-10"><div><h1 className="text-4xl font-black leading-tight text-abla-blue">Un compañero reconocible en cada momento</h1><p className="mt-4 max-w-2xl leading-7 text-slate-500">Validación interna de silueta, proporciones, mirada y consistencia. Esta ruta solo existe en desarrollo.</p></div><div className="grid place-items-center"><AblaCompanion size="hero" personality="friendly" interactive label="Compañero ABLA" /></div></div><ShowcaseRow title="Personalidades" items={personalities} render={(item) => <AblaCompanion size="lg" personality={item} accessory={item === 'protective' ? 'shield' : 'none'} interactive />} /><ShowcaseRow title="Emociones" items={moods} render={(item) => <AblaCompanion size="lg" mood={item} />} /><ShowcaseRow title="Ojos" items={eyeExpressions} render={(item) => <AblaCompanion size="lg" eyeExpression={item} mouthExpression="neutral" gaze={item === 'side' ? 'right' : 'center'} />} /><ShowcaseRow title="Bocas" items={mouthExpressions} render={(item) => <AblaCompanion size="lg" eyeExpression="open" mouthExpression={item} />} /><ShowcaseRow title="Poses" items={companionPoses} render={(item) => <AblaCompanion size="lg" pose={item} mood={item === 'celebrating' ? 'excited' : 'happy'} />} /><ShowcaseRow title="Accesorios" items={companionAccessories.filter((item) => item !== 'none')} render={(item) => <AblaCompanion size="lg" personality={item === 'shield' ? 'protective' : 'friendly'} accessory={item} interactive />} /></div></main>
}
